### ISSUE TITLE
Subscribing to "balances" channel using KrakenSpotWSClientV2 fails

### ISSUE THREAD

**Issue by Trevypants** [btschwertfeger/python-kraken-sdk#227]
**Describe the bug**
I am running into issues with subscribing to the `balances` channel using the v2 websocket client. I receive two types of errors:

1. A "Private data and trading are unavailable on this endpoint. Try ws-auth.kraken.com" error. This occurs when I create an authenticated client and subscribe to the `balances` channel.

2. An "AttributeError: Could not found any connected websocket!". This occurs when I create an authenticated client with `no_public=True`.

**To Reproduce**
1. A "Private data and trading are unavailable on this endpoint. Try ws-auth.kraken.com" error.

```python
import asyncio
from kraken.spot import KrakenSpotWSClientV2

KRAKEN_API_KEY="***"
KRAKEN_PRIVATE_KEY="***"

class Client(KrakenSpotWSClientV2):
    async def on_message(self, message):
        """Receives the websocket messages"""
        if message.get("method") == "pong" or message.get("channel") == "heartbeat":
            return

        print(message)

async def main():
    client_auth = Client(
        key=kraken_api_key,
        secret=kraken_private_key,
        no_public=False,
    )

    # Subscribe to Balance Updates
    await client_auth.subscribe(
        params={
            "channel": "balances",
            "snapshot": False,
        }
    )

    await asyncio.sleep(10)

    # Unsubscribe from Balance Updates
    await client_auth.unsubscribe(
        params={
            "channel": "balances",
            "snapshot": False,
        }
    )

if __name__ == "__main__":
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        loop.close()
```

2. An "AttributeError: Could not found any connected websocket!". 

```python
import asyncio
from kraken.spot import KrakenSpotWSClientV2

KRAKEN_API_KEY="***"
KRAKEN_PRIVATE_KEY="***"

class Client(KrakenSpotWSClientV2):
    async def on_message(self, message):
        """Receives the websocket messages"""
        if message.get("method") == "pong" or message.get("channel") == "heartbeat":
            return

        print(message)

async def main():
    client_auth = Client(
        key=kraken_api_key,
        secret=kraken_private_key,
        no_public=True,
    )

    # Subscribe to Balance Updates
    await client_auth.subscribe(
        params={
            "channel": "balances",
            "snapshot": False,
        }
    )

    await asyncio.sleep(10)

    # Unsubscribe from Balance Updates
    await client_auth.unsubscribe(
        params={
            "channel": "balances",
            "snapshot": False,
        }
    )

if __name__ == "__main__":
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        loop.close()
```

**Expected behavior**
I expected that the websocket connection would open as usual and that I would start receiving streams.

**Environment (please complete the following information):**

- OS: [MacOS Sonoma 14.4.1]
- Python [3.11]

**Comment by btschwertfeger** [comment]
Hey @Trevypants, thank you for your hints!

I haven't noticed, that the documentation at https://docs.kraken.com/websockets-v2 is deprecated and have now found this here: https://docs.kraken.com/api/docs/websocket-v2/balances. The balances channels seems to be quite new.

I adjusted the implementation accordingly (#229) and will publish the fix soon.

The second error you described was caused by the same problem, since the new "balances" channel is missing in https://github.com/btschwertfeger/python-kraken-sdk/blob/v2.2.0/kraken/spot/websocket_v2.py#L548, causing the python-kraken-sdk to assume, that balances is a public channel - which of course fails, since the public websocket connection was not created due to ``no_public=True`` 

I wish there was a more generic way to distinguish between authenticated and unauthenticated channels...
